In [ ]:
def add(a,b):      #function def    a=10,  b=20
  result=a+b       #write formula   a+b=10+20=30,
  print(result)    #result=30

In [ ]:
add(10,20)   #variable a=value store Function Calling
add(12,22)   #
add(55,52)
add(105,52)

30
34
107
157


In [ ]:
def Pdosage(weight):
  dosage=weight*10
  return dosage

In [ ]:

result= Pdosage(55) #55*10=550
finaldose=result/2
print(finaldose)


275.0


In [ ]:
medicine=['Paracetamol', 'Ibuprofen', 'Amoxicillin', 'Cetirizine'] # List Data Structure
print(medicine)
medicine[0] #para
medicine[3] #cet
medicine.append('Ceterizine') # insert data at the end of list

['Paracetamol', 'Ibuprofen', 'Amoxicillin', 'Cetirizine']


In [ ]:
medicine.insert( 2, 'Crocin') #insert data with index of list
medicine

['Paracetamol',
 'Ibuprofen',
 'Crocin',
 'Amoxicillin',
 'Cetirizine',
 'Ceterizine']

In [ ]:
medicine.remove('Ibuprofen') # remove delete data from list
medicine

['Paracetamol', 'Crocin', 'Amoxicillin', 'Cetirizine', 'Ceterizine']

In [ ]:
medicine.sort()
medicine

['Amoxicillin', 'Ceterizine', 'Cetirizine', 'Crocin', 'Paracetamol']

In [ ]:
len(medicine)

5

In [ ]:
medicine

['Amoxicillin', 'Ceterizine', 'Cetirizine', 'Crocin', 'Paracetamol']

In [ ]:
medicine[ 1:3 ]

['Ceterizine', 'Cetirizine']

In [ ]:
medicine[ : :2 ]

['Amoxicillin', 'Cetirizine', 'Paracetamol']

In [ ]:
medicine[ ::-1 ]

['Paracetamol', 'Crocin', 'Cetirizine', 'Ceterizine', 'Amoxicillin']

In [ ]:
bloodsample=('A','B','AB','O')
bloodsample[3]

'O'

In [ ]:
len(bloodsample)

4

In [ ]:
#dictionary create
Patient = { "ID":"P01",
            "Name":"Suchita",
            "Age":35
          }
Patient

{'ID': 'P01', 'Name': 'Suchita', 'Age': 35}

In [ ]:
#dictionary Access Key only: value print
print(Patient["Name"])
print(Patient["ID"])
print(Patient["Age"])

Suchita
P01
35


In [ ]:
# Add key:value
Patient["weight"]=65
print(Patient)

{'ID': 'P01', 'Name': 'Suchita', 'Age': 35, 'weight': 65}


In [ ]:

Patient["Blood Group"]='B'
print(Patient)

{'ID': 'P01', 'Name': 'Suchita', 'Age': 35, 'weight': 65, 'Blood Group': 'B'}


In [ ]:
#modify value
Patient['Name']="MOnika"
print(Patient)

{'ID': 'P01', 'Name': 'MOnika', 'Age': 35, 'weight': 65, 'Blood Group': 'B'}


In [ ]:
# delete key:value
del Patient['Blood Group']
print(Patient)

{'ID': 'P01', 'Name': 'MOnika', 'Age': 35, 'weight': 65}


In [ ]:
#dispaly key value
Patient.values()
print(Patient)

{'ID': 'P01', 'Name': 'MOnika', 'Age': 35, 'weight': 65}


In [ ]:
#clear dictionary {}
Patient.clear()
print(Patient)

{}


In [ ]:
#numpy library
import numpy as np
weight=np.array([55,60,65,70,88,66,47,35,98,56,32,98,77])
weight

array([55, 60, 65, 70, 88, 66, 47, 35, 98, 56, 32, 98, 77])

In [ ]:
dose=weight*10
dose

array([550, 600, 650, 700, 880, 660, 470, 350, 980, 560, 320, 980, 770])

In [ ]:
weight
print(np.max(weight))
print(np.min(weight))
print(np.mean(weight))
print(np.std(weight))

98
32
65.15384615384616
20.372855824303816


In [ ]:
print(weight)
print(dose)

[55 60 65 70 88 66 47 35 98 56 32 98 77]
[550 600 650 700 880 660 470 350 980 560 320 980 770]


In [ ]:
weight+dose

array([ 605,  660,  715,  770,  968,  726,  517,  385, 1078,  616,  352,
       1078,  847])

In [ ]:
weight-dose

array([-495, -540, -585, -630, -792, -594, -423, -315, -882, -504, -288,
       -882, -693])

In [ ]:
weight*dose

array([30250, 36000, 42250, 49000, 77440, 43560, 22090, 12250, 96040,
       31360, 10240, 96040, 59290])

In [ ]:
weight/dose

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])